apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data: #L'env minikube est Horsligne, ces fichiers ont juste pour but de tester K8
    mongo-root-username: dXNlcm5hbWU=
    mongo-root-password: cGFzc3dvcmQ=